sudo: required
os: linux
dist: trusty
services:
- docker
language: bash
git:
  depth: 1

branches:
  only:
  - master
  - /^ci-.*$/

install:
- sudo apt-get update
- sudo apt-get install --yes docker-ce

env:
  matrix:
  - SERVICE=alertmanager
  - SERVICE=caddy
  - SERVICE=dante
  - SERVICE=grafana       MAKEFLAGS="-j 2" # Run jobs in parallel as grafana build takes a lot of time
  - SERVICE=metrics-node-exporter
  - SERVICE=node-exporter
  - SERVICE=openvpn
  - SERVICE=prometheus

script:
- make build-${SERVICE}
- make push-${SERVICE}
- make tag-${SERVICE}
- make tag-${SERVICE}
- make push-manifest-${SERVICE}-sha
- make push-manifest-${SERVICE}

notifications:
  email: false
  slack:
    # nofitication
    secure: N4SeKE16m4R7fejlxzCwUaPQLh6c/4PhVq02QAe9ejZ0B8YFmMwUcTnPYi1gLDk0TtlOWf3g+dqHLRY1J27HkVqGu0V+0BA+al1rJMu04PVCbVf2noFydbvlGzvb314PmfztA2VpI2p/gchZbSuaURL5a+H9vvYehQjxrld2Ull5OE5vb7zwbPWzBvTFo7R/Q0VTEx8aPUnXnEXFe87y4t2wg465x19MjllRCA0N4teZli3cVfT2fmLN4qfFSUfvPYfQLfjWuz2wc+vyAikSyvSpsLHco0AQtxMpWTjdDXHqwkg1/iQWCE8YuxS/1Qf+mLWONR0+CcP4cJzF4NaohykYkCeJ1EARxIvdUBSlzkMmgeYwfVf0U4MUkb8+9xZgYkBR6NgRNvTvYMjG6AI2b0tgPub2QIt8sk0Mll+3IIw6+h+h/MdHVe/J2b+OycLkfWd3ixrhtEz43HAjeY/A9rfKQ2XR5f7SHk8Jtg7nFez+G5xCrluHdISJs+fbzCyPsSOzWen3w1V5UEwdtoRPbVSz0LJCs08ukQ4GPTPvCwQaPRnWK0V6408LSmlKQuDO3EWDrW7S/qnMmjKmdYbLpvB0xYOOzRv8VUOdKudGMIDDP1h9MrYahGwVfLuOeL9Wjlnpufy51u2B6g2y5mzT5T+fUgxDPt6AQS5qSyYoL1E=
