networks:
  monitor-net:
    driver: bridge

services:
  alertmanager:
    expose:
    - 9093
    image: macisamuele/alertmanager:latest
    labels:
      org.label-schema.group: "monitoring"
    networks:
    - monitor-net
    restart: on-failure:3
    volumes:
    - ${CONFIG_FILES}/monitoring/alertmanager.yml:/etc/alertmanager/config.yml:ro  # This is needed in order to not publish slack secrets on github :)

  caddy:
    expose:
    - 3000
    - 9090
    - 9093
    - 9100
    image: macisamuele/caddy:latest
    labels:
      org.label-schema.group: "monitoring"
    networks:
    - monitor-net
    ports:
    - 3000:3000
    - 9090:9090
    - 9093:9093
    - 9100:9100
    restart: on-failure:3

  metrics-node-exporter:
    image: macisamuele/metrics-node-exporter:latest
    labels:
      org.label-schema.group: "monitoring"
    networks:
    - monitor-net
    restart: on-failure:3
    privileged: true
    environment:
      DAEMON_INTERVAL: '2'
      OUTPUT_FILE: /metrics_data/data.prom
    volumes:
    - metrics_node_exporter_data:/metrics_data/
    - /dev/vchiq:/dev/vchiq:ro

  grafana:
    expose:
    - 3000
    image: macisamuele/grafana:latest
    labels:
      org.label-schema.group: "monitoring"
    networks:
    - monitor-net
    restart: on-failure:3
    volumes:
    - grafana_data:/grafana/data:rw

  node-exporter:
    expose:
    - 9100
    image: macisamuele/node-exporter:latest
    labels:
      org.label-schema.group: "monitoring"
    networks:
    - monitor-net
    privileged: true
    restart: on-failure:3
    volumes:
    - /:/rootfs:ro
    # - /cgroup:/cgroup:ro # It does work only for Linux with cgroup enabled -> doesn't work on MacOS and raspian
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - metrics_node_exporter_data:/file_metrics:ro

  prometheus:
    expose:
    - 9090
    image: macisamuele/prometheus:latest
    labels:
      org.label-schema.group: "monitoring"
    networks:
    - monitor-net
    restart: on-failure:3
    volumes:
    - prometheus_data:/prometheus:rw

version: '3.6'

volumes:
  metrics_node_exporter_data: {}
  grafana_data: {}
  prometheus_data: {}
