FROM golang:1.10.1-stretch AS cadvisor_builder
LABEL MAINTAINER="Samuele Maci <macisamuele@gmail.com>"
LABEL DESCRIPTION="[Monitoring Tools - Builder] cadvisor"
LABEL PLATFORM="armhf"

ENV GOARCH=arm \
    GOARM=7 \
    GOOS=linux \
    CGO_ENABLED=1 \
    CC=arm-linux-gnueabi-gcc

RUN set -eux && \
    apt-get update && \
    DEBIAN_FRONTEND=interactive apt-get install -y gcc-arm-linux-gnueabi && \
    go get -ldflags '-extldflags "-static"' github.com/google/cadvisor


FROM arm32v7/debian:stretch-slim AS cadvisor
LABEL MAINTAINER="Samuele Maci <macisamuele@gmail.com>"
LABEL DESCRIPTION="[Monitoring Tools] cadvisor"
LABEL PLATFORM="armhf"

# Add qemu-*-static to allow execution of the build process from any platform
COPY qemu-*-static /usr/bin

# Create container user
ENV RUN_USER cadvisord
RUN adduser \
    --home /non_existing \
    --gecos "${RUN_USER} user" \
    --shell '/bin/bash' \
    --disabled-login \
    --disabled-password \
    ${RUN_USER}

# Copy cadvisor binaries
COPY --from=cadvisor_builder /go/bin/* /bin/

# Container port, privileges and volumes
EXPOSE 8080
USER ${RUN_USER}
# NOTE: VOLUME is not defined as cadvisor configurations
#       are provided by the command line only
#       If the defined configs does not match you needs
#       make sure to override the default command below

# Default command
CMD [ \
    "/bin/cadvisor",  \
        "-alsologtostderr", \
        "-global_housekeeping_interval", "5m0s", \
        "-housekeeping_interval", "5m0s", \
        "-log_cadvisor_usage", \
        "-max_housekeeping_interval", "5m0s", \
        "-max_procs", "1" \
]

