FROM amd64/debian:stretch-slim AS metrix_extractor
LABEL MAINTAINER="Samuele Maci <macisamuele@gmail.com>"
LABEL DESCRIPTION="[Monitoring Tools] metrix_extractor"
LABEL PLATFORM="amd64"

# Add qemu-*-static to allow execution of the build process from any platform
COPY qemu-*-static /usr/bin/

ADD daemon.sh /code/daemon.sh
ADD amd64-metrics.sh /code/metrics.sh

CMD [ "/bin/sh", "/code/daemon.sh" ]
